import Layout from "@/components/layouts/Layout";
import type { Metadata } from "next";
import "./globalStyles/globals.css";
import "./globalStyles/header.css";
import "./globalStyles/menu.css";
import "./globalStyles/normalize.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Online Market ",
  description: "Generated by create next app",
};
